<h1 class="app-h1">Edit Customer</h1>



<div class="row mt-5">
    <div class="col-md-10">
        <form action="/customers/update/<?= $this->clearInt($customer->id); ?>" method="post">





            <div class="form-group row">
                <label class="col-form-label col-md-2" for="name">Name:</label>
                <div class="col-md-10">
                    <input type="text" id="name" class="form-control" name="name" value="<?= $this->clearStr($customer->name); ?>" required>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2" for="email">Email:</label>
                <div class="col-md-10">
                    <input type="email" id="email" class="form-control" name="email" value="<?= $this->clearStr($customer->email); ?>" required>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2" for="state">State:</label>
                <div class="col-md-10">
                    <select class="form-control" name="state" id="state" required>
                        <?php foreach ($states as $state) : ?>
                            <?php if ($state == $this->clearStr($customer->state)) : ?>
                                <option value="<?= $this->clearStr($state); ?>" selected><?= $this->clearStr($state); ?></option>
                            <?php else: ?>
                                <option value="<?= $this->clearStr($state); ?>"><?= $this->clearStr($state); ?></option>
                            <?php endif; ?>

                        <?php endforeach; ?>
                    </select>
                </div>
            </div>





            <div class="form-group row">
                <!-- &nbsp in order Public not to jump over to the next line when the width of the page is small -->
                <label class="col-sm-2 col-3" for="interested">Interested:</label>
                <div class="col-sm-10 col-9">
                    <label class="custom-control custom-checkbox">
                        <input type="checkbox"
                               class="custom-control-input"
                               id="interested"
                               name="interested"
                               value="1" <?= $this->clearStr($customer->interested) ? 'checked ': ''; ?>
                        >
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-description"></span>
                    </label>
                </div>
            </div>

            <br>
            <div class="row">
                <div class="col-md-12 offset-md-2">
                    <input type="submit" value="Update" name="edit_customer" class="btn btn-outline-primary">
                </div>
            </div>

        </form>
    </div>
</div>
