<h1 class="app-h1">Manage Customers</h1>

<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>State</th>
                    <th>Interested</th>
                    <th>Actions</th>
                </tr>
                <?php foreach ($customers as $customer) : ?>
                    <tr>
                        <td><?= ++$cnt ?></td>
                        <td><?= $this->clearStr($customer->name); ?></td>
                        <td><?= $this->clearStr($customer->email); ?></td>
                        <td><?= $this->clearStr($customer->state); ?></td>
                        <td><?= $this->clearStr($customer->interested) ? 'Yes' : 'No'; ?></td>
                        <td>
                            <a href="customers/edit/<?= $this->clearInt($customer->id) ?>">Edit</a>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <form action="customers/delete/<?= $this->clearInt($customer->id) ?>" method="post" class="form-delete confirm-plugin">

                                <button type="submit" name="delete" value="submit">Delete</button>
                            </form>
                        </td>



                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
